import{a as q,S as P,i as l}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function h(i,o=1){const t=`https://pixabay.com/api/?key=51593230-95869a69d21a93ebacba8501d&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`;return(await q.get(t)).data}const y=document.querySelector(".gallery");let $=new P(".gallery a",{captionsData:"alt",captionsDelay:250});function p(i){const o=i.map(({webformatURL:s,largeImageURL:r,tags:e,likes:t,views:n,comments:w,downloads:v})=>`
      <li class="gallery-item">
      <a href="${r}" class="gallery-item">
      <div class="image-card">
        <img src="${s}" alt="" loading="lazy" />
        <ul class="image-stats">
          <li><b>Likes</b> ${t}</li>
          <li><b>Views</b> ${n}</li>
          <li><b>Comments</b> ${w}</li>
          <li><b>Downloads</b> ${v}</li>
        </ul>
      </div>
    </a>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",o),$.refresh()}function R(){y.innerHTML=""}function L(){document.querySelector(".loader").classList.remove("hidden")}function d(){document.querySelector(".loader").classList.add("hidden")}function b(){document.querySelector(".load-more").classList.remove("hidden")}function c(){document.querySelector(".load-more").classList.add("hidden")}function E(){document.querySelector(".text-note").classList.remove("hidden")}function u(){document.querySelector(".text-note").classList.add("hidden")}c();u();d();const A=document.querySelector(".form"),m=document.querySelector(".input"),_=document.querySelector(".load-more"),S=15;let a=1,g="",f=0;A.addEventListener("submit",async function(o){o.preventDefault();const s=m.value.trim();if(!s){l.info({title:"Empty",message:"Type something to search.",position:"topRight",color:"orange"});return}g=s,a=1,R(),c(),L(),u();try{const r=await h(g,a);f=r.totalHits,await new Promise(e=>setTimeout(e,2e3)),r.hits.length===0?(l.warning({title:"No results",message:`No images found for "${s}".`,position:"topRight",color:"red"}),m.value=""):(p(r.hits),a*S<f?(b(),u()):(c(),E()),m.value="")}catch(r){l.error({title:"Error",message:`Something went wrong: ${r.message}.`,position:"topRight"})}finally{d()}});_.addEventListener("click",async()=>{a+=1,L(),c();try{const i=await h(g,a);p(i.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"});const s=a*S;if(d(),s<f)b(),u();else{c(),E(),l.info({title:"End of search",message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"orange"});return}}catch(i){l.error({title:"Error",message:`Failed to load more: ${i.message}.`,position:"topRight"})}finally{d()}});
//# sourceMappingURL=index.js.map
