import{a as v,S as P,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function y(i,o=1){const t=`https://pixabay.com/api/?key=51593230-95869a69d21a93ebacba8501d&q=${encodeURIComponent(i)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`;return(await v.get(t)).data}const h=document.querySelector(".gallery");document.querySelector(".load-more");let $=new P(".gallery a",{captionsData:"alt",captionsDelay:250});function p(i){const o=i.map(({webformatURL:s,largeImageURL:r,tags:e,likes:t,views:n,comments:w,downloads:q})=>`
      <li class="gallery-item">
      <a href="${r}" class="gallery-item">
      <div class="image-card">
        <img src="${s}" alt="" loading="lazy" />
        <ul class="image-stats">
          <li><b>Likes</b> ${t}</li>
          <li><b>Views</b> ${n}</li>
          <li><b>Comments</b> ${w}</li>
          <li><b>Downloads</b> ${q}</li>
        </ul>
      </div>
    </a>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",o),$.refresh()}function R(){h.innerHTML=""}function L(){document.querySelector(".loader").classList.remove("hidden")}function f(){document.querySelector(".loader").classList.add("hidden")}function S(){document.querySelector(".load-more").classList.remove("hidden")}function l(){document.querySelector(".load-more").classList.add("hidden")}function b(){document.querySelector(".text-note").classList.remove("hidden")}function d(){document.querySelector(".text-note").classList.add("hidden")}l();d();f();const A=document.querySelector(".form"),u=document.querySelector(".input"),I=document.querySelector(".load-more"),E=15;let a=1,m="",g=0;A.addEventListener("submit",async function(o){o.preventDefault();const s=u.value.trim();if(!s){c.info({title:"Empty",message:"Type something to search.",position:"topRight",color:"orange"});return}m=s,a=1,R(),l(),L(),d();try{const r=await y(m,a);g=r.totalHits,await new Promise(e=>setTimeout(e,2e3)),r.hits.length===0?(c.warning({title:"No results",message:`No images found for "${s}".`,position:"topRight",color:"red"}),u.value=""):(p(r.hits),a*E<g?(S(),d()):(l(),b()),u.value="")}catch(r){c.error({title:"Error",message:`Something went wrong: ${r.message}.`,position:"topRight"})}finally{f()}});I.addEventListener("click",async()=>{a+=1,L(),l();try{const i=await y(m,a);p(i.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),a*E<g?(S(),d()):(l(),b())}catch(i){c.error({title:"Error",message:`Failed to load more: ${i.message}.`,position:"topRight"})}finally{f()}});
//# sourceMappingURL=index.js.map
